### PR TITLE
Domain update

### PR DESCRIPTION
**Pull request by rrusher**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/en-ca/trucks/powertrain/d11
- After: https://domain-update--vg-volvotrucks-us--hlxsites.hlx.page/en-ca/trucks/powertrain/d11

- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/en-ca/trucks/powertrain/d13
- After: https://domain-update--vg-volvotrucks-us--hlxsites.hlx.page/en-ca/trucks/powertrain/d13

The performance charts display.
The links should have the trailing slash removed.

### CODE REVIEW

**Comment by dkuntze** [comment]
@rrusher is this for the ca domain?

**Comment by synox** [comment]
@rrusher i am confused, shouldn’t this change go into the volvotrucks-ca git repository?

**Comment by rrusher** [comment]
@synox That's correct. It is supposed to be in the Canada repo.

**Comment by rrusher** [comment]
work repo

**Pull request closed without merging**
